architect:
  - caarlos0
merge:
  script:
    - git submodule init
    - git submodule update
    - sudo apt-get install ghc cabal-install -y
    - cabal update
    - cabal install shellcheck
    - export PATH="/home/r/.cabal/bin:$PATH"
    - ./build.sh
release:
  script:
    - git submodule init
    - git submodule update
    - sudo apt-get install ghc cabal-install -y
    - cabal update
    - cabal install shellcheck
    - export PATH="/home/r/.cabal/bin:$PATH"
    - ./build.sh
