architect:
  - caarlos0
merge:
  script:
    - git submodule init
    - git submodule update
    - sudo apt-get install ghc cabal-install -y
    - cabal install shellcheck
    - ./build.sh
release:
  script:
    - git submodule init
    - git submodule update
    - sudo apt-get install ghc cabal-install -y
    - cabal install shellcheck
    - ./build.sh
