language: bash

install:
  - sudo apt-get update
  - sudo apt-get install -y ghc6 ghc6-prof ghc6-doc cabal-install
  - cabal update
  - cabal install shellcheck
  - sudo ln ~/.cabal/bin/shellcheck /usr/bin/shellcheck

script:
  - ./build.sh
