language: ruby
rvm:
  - 2.0.0
os:
  - linux
  - osx
install: |
  set -e
  ./build/install.sh
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo apt-get update
    sudo apt-get install -y zsh
  fi
  sudo wget -O /usr/local/bin/shfmt https://github.com/mvdan/sh/releases/download/v1.3.1/shfmt_v1.3.1_$(uname -s | tr '[:upper:]' '[:lower:]')_amd64
  sudo chmod +x /usr/local/bin/shfmt
  zsh --version
  shfmt --version
  shellcheck --version
script:
  - ./script/test
notifications:
  email: false
