language: ruby
rvm:
  - 2.0.0
os:
  - linux
  - osx
install: |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get update >/dev/null
    sudo apt-get install -y zsh
  else
    brew update >/dev/null
    brew install shellcheck shfmt zsh
  fi
script:
  - curl -sL https://git.io/shcheck | bash -x -s -- \
      --ignore 'script/test' \
      --ignore 'vim/vim.symlink/**/*' \
      --ignore 'zsh/config.zsh' \
      --ignore 'zsh/completion.zsh' \
      --ignore 'zsh/prompt.zsh' \
      --ignore 'zsh/fpath.zsh' \
      --ignore 'docker/completion.zsh' \
      --ignore 'atom.symlink/packages/**/*'
  - ./script/test
notifications:
  email: false
